### ISSUE TITLE
Clarify Licensing of Code

### ISSUE THREAD

**Issue by Perni1984** [mcqua007/shopify-bare#1]
Hi @mcqua007,

I am glad that somebody took the time to develop a nice and decent frontend workflow from shopify. We are using shopify ourselves and are looking for such a solution. Unfortunately I have nowhere found the license you released the code under. 

Could you kindly clarify under what license your code is released and eventually also mention the license in the github project?

Thanks!

Christoph

**Comment by mcqua007** [comment]
Hello @Perni1984,
Sorry it was missing. I just updated the repo with the **MIT license.**  [Listed here ](https://github.com/mcqua007/shopify-bare/blob/master/LICENSE)
Thanks for bringing this to my attention.`

**Comment by mcqua007** [comment]
@Perni1984 I should let you know that I ended up  fixing the bug that caused the most annoyance and pushed the change in the v1.0.0. Now that I got that fix done things should be stable though I may add more features (i.e. possibly hot reloading with live reload). So be sure to keep checking in.
